import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
import {createOffice} from './scene.js?v=3';
import {panels} from './panels.js?v=7';
import {createChinches3D} from './chinches3d.mjs?v=1';
import {createOfficePilot,chooseOfficeHit} from './avatars/office-pilot.mjs';
const $=s=>document.querySelector(s),mount=$('#scene'),coarse=matchMedia('(pointer:coarse)').matches;
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('#loading').hidden=true;$('#fallback').hidden=false;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,coarse?1.25:1.65));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.10;mount.appendChild(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#e3dfd7');scene.fog=new T.Fog('#e3dfd7',60,180);
const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;scene.environmentIntensity=.23;room.dispose();pmrem.dispose();
const camera=new T.PerspectiveCamera(43,1,.08,240),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.dampingFactor=.11;orbit.enablePan=false;orbit.minDistance=8;orbit.maxDistance=150;orbit.maxPolarAngle=Math.PI*.465;orbit.minPolarAngle=.15;orbit.rotateSpeed=.58;orbit.zoomSpeed=.7;
scene.add(new T.HemisphereLight('#f5f2e9','#98968a',1.45));const sun=new T.DirectionalLight('#fff1d9',2.4);sun.position.set(-10,22,10);sun.castShadow=true;sun.shadow.mapSize.set(coarse?1024:2048,coarse?1024:2048);Object.assign(sun.shadow.camera,{left:-31,right:25,top:25,bottom:-25,near:1,far:60});sun.shadow.normalBias=.035;sun.shadow.bias=-.0002;sun.shadow.radius=3;scene.add(sun);const fill=new T.DirectionalLight('#dce8ec',.8);fill.position.set(10,10,-9);scene.add(fill);
let office;try{office=await createOffice({pilotFigure:false});scene.add(office.model);}catch(e){$('#loading').hidden=true;$('#fallback').hidden=false;throw e;}
const places={
 editing:{label:'Sala de edición',eye:[-18,1.65,.7],target:[-18,1.7,-6.9]},
 editorial:{label:'Mesa editorial',eye:[-21,1.65,-5.8],target:[-20.7,1.9,-7.9]},
 funnel:{label:'Embudo comercial',eye:[-15.1,1.65,-5.8],target:[-15.25,1.9,-7.9]},
 entry:{label:'Entrada al Despacho',eye:[-4.8,1.65,7.7],target:[-1,1.5,-3.5]},
 reception:{label:'Recepción',eye:[-8.3,1.65,-4.5],target:[-8.2,1.8,-8.5]},
 patio:{label:'Patio central',eye:[-4.45,1.65,.7],target:[0,1.6,-1]},
 potential:{label:'Potenciales',eye:[8.65,1.65,-4.55],target:[8.3,1.1,-7.2]},
 case:{label:'Mi terreno · Caso',eye:[8.0,1.65,-4.45],target:[6.65,1.3,-4.42]},
 projects:{label:'Proyectos y permisos',eye:[8.5,1.65,1.65],target:[8.5,1.1,-1.6]},
 delivery:{label:'Obra y ventas',eye:[8.5,1.65,7.7],target:[8.5,1.1,4.8]},
 decisions:{label:'Decisiones',eye:[3.4,1.65,6.5],target:[-.2,1.1,6.3]},
 lounge:{label:'Sala de encuentro',eye:[-5.65,1.65,4.1],target:[-8.5,1.1,2.9]}
};
panels.reception={tag:'Recepción · YoDesarrollo',title:'Un Despacho que puede crecer.',body:'<p>Una recepción de madera y piedra, la marca YoDesarrollo y una circulación clara hacia los estudios de trabajo.</p><p>El diseño amplía el espacio aprobado e incorpora las referencias de Aurum en las curvas, los materiales y la relación con el patio.</p><p class="note">Versión 02. Por ahora sólo se muestra la ficha de Caso; las tareas de MOAC aún no están conectadas.</p><a href="diseno.html">Ver las referencias de Aurum</a>'};
panels.patio={tag:'Patio central',title:'El punto de encuentro.',body:'<p>Un olivo, piedra natural y vegetación baja organizan el centro del Despacho. Los pasillos a ambos lados permiten recorrer las áreas sin pasar entre los puestos de trabajo.</p><p>El patio sirve como referencia para orientarte en todo momento.</p>'};
panels.potential={tag:'Estudio 01 · Potenciales',title:'Aquí comienza cada terreno.',body:'<p>Un área para entender el predio, verificar sus posibilidades y preparar el Plan de Potencial.</p><h3>En esta prueba</h3><p>Mi terreno, Caso, tiene aquí su lugar. Puedes abrir su ficha desde el botón inferior o tocar a su personaje.</p><p class="note">La distribución permitirá trabajar por grupos de casos, manteniendo despejados los recorridos. Esta versión no carga otras tareas.</p>'};
panels.projects={tag:'Estudio 02',title:'Proyectos y permisos.',body:'<p>Espacio previsto para los casos que avanzan en diseño, normativa, trámites y permisos.</p><p>Los puestos se agrupan alrededor de un área propia, con separación visual respecto al estudio de Potenciales.</p><p class="note">Área preparada para la futura conexión de MOAC. No contiene tareas activas en esta versión.</p>'};
panels.delivery={tag:'Estudio 03',title:'Obra y ventas.',body:'<p>Espacio previsto para dar seguimiento a ejecución y comercialización, conservando el vínculo con el mismo terreno y su historia.</p><p class="note">La asignación de tareas a esta área se conectará con MOAC; los puestos actuales no representan tareas cargadas.</p>'};
panels.lounge={tag:'Sala de encuentro',title:'Revisar con otra perspectiva.',body:'<p>Una sala para conversaciones y revisión conjunta, con mobiliario tapizado, madera, piedra y una biblioteca de proyectos.</p><p>Permite reunir a quienes participan en un caso sin ocupar su área de trabajo.</p>'};

panels.editing={tag:'Sala de edición · Embudo comercial',title:'Producir, revisar y aprender.',body:'<p>Un ala propia para reunir la producción de contenido y la visión comercial de YoDesarrollo y Aurum.</p><h3>La mesa de Alejandro y Sayri</h3><p>Dos lugares para revisar propuestas, pedir cambios y tomar decisiones editoriales. Los clientes y socios pueden participar como lectores; la producción propone y reporta.</p><h3>Los puestos de trabajo</h3><ul><li><b>Guion y propuesta:</b> ideas, mensaje, audiencia y objetivo.</li><li><b>Producción:</b> guion, láminas, voz y video, con sus versiones.</li><li><b>Comercial y medición:</b> campañas, publicaciones, pauta, leads, citas y seguimiento.</li></ul><h3>Dos pantallas, una visión común</h3><p>La mesa editorial muestra qué falta revisar. El embudo muestra el recorrido desde el inicio, incluyendo las caídas entre etapas, y los dos imanes: Arquitectura de Autor y Plan de Potencial.</p><p class="note">Distribución basada en los procesos documentados de Sala de Edición y Embudo comercial. Las pantallas son un esquema; no muestran cifras ni ejecutan decisiones.</p><p><a href="https://yodesarrollomx.github.io/sala-edicion/" target="_blank" rel="noopener">Abrir la Sala de Edición actual</a></p><p><a href="https://yodesarrollomx.github.io/aurum-board/" target="_blank" rel="noopener">Abrir el Embudo comercial actual</a></p>'};
panels.editorial={tag:'Pantalla de revisión editorial',title:'Lo que necesita una decisión.',body:'<p>Propuestas → decisión editorial → producción por etapas → correcciones → aprobación final.</p><p>Los guiones se leen, las láminas se ven, las voces se escuchan y el video se revisa en movimiento. La sala reserva una pantalla amplia y la mesa de los dos editores para respetar cada formato.</p><p>Una pieza con una petición abierta necesita resolverla antes de avanzar.</p><p class="note">Esquema del proceso documentado. La conexión con las propuestas y decisiones reales será otro bloque.</p>'};
panels.funnel={tag:'Pantalla del embudo comercial',title:'Del primer contacto al siguiente paso.',body:'<p>Aquí se reunirán las publicaciones de Facebook e Instagram, el gasto de pauta, los leads y las citas, y los recorridos de Arquitectura de Autor y Plan de Potencial.</p><p>La vista debe comenzar en Inicio y mostrar también los abandonos. No confundiremos una cita con una venta ni atribuiremos un cierre a una campaña sin evidencia.</p><p class="note">La documentación acredita esos módulos; en este bloque no se comprobó su ejecución en vivo ni se cargaron métricas.</p>'};

panels.editing={tag:'Sala de edición · Embudo comercial',title:'Tu mesa de trabajo.',body:'<p>Revisión editorial, producción y seguimiento comercial con acceso a los tableros actuales.</p><p><a href="sala.html">Entrar a la mesa de trabajo</a></p><p class="note">Los datos y las decisiones permanecen en sus sistemas de origen. La oficina todavía no los carga en vivo.</p>'};
panels.editorial={tag:'Mesa de Alejandro y Sayri',title:'Revisión editorial.',body:'<p>Propuestas, correcciones y aprobación de las etapas de producción.</p><p><a href="sala.html#editorial">Abrir revisión editorial</a></p>'};
panels.funnel={tag:'Comercial y medición',title:'El embudo completo.',body:'<p>Consulta publicaciones, pauta, leads, citas y seguimiento en el tablero comercial.</p><p><a href="sala.html#comercial">Abrir estación comercial</a></p>'};

let chinches=null;
let agentOverlay=false;
let mode='overview',selected='entry',yaw=0,pitch=0,near=null,sheet=null,look=null,stickId=null,stick={x:0,y:0},keys=new Set(),last=performance.now(),frames=0,transitionToken=0,dirty=true,lastFocus=null;
const reducedMotion=matchMedia('(prefers-reduced-motion:reduce)');
let avatarShadowAt=0;
const pilot=createOfficePilot({scene,beforeOpen:()=>closeSheets(false),onChange:()=>{dirty=true;renderer.shadowMap.needsUpdate=true;avatarShadowAt=performance.now();}});
const bindPilot=()=>pilot.bind(window.CubefarmYOD);
window.addEventListener('yod-agents-ready',bindPilot);
window.addEventListener('pagehide',()=>pilot.disconnect());
window.addEventListener('pageshow',bindPilot);
bindPilot();
function isMobile(){return innerWidth<=700||coarse;}
function updateAngles(target){const d=new T.Vector3().subVectors(target,camera.position);yaw=Math.atan2(-d.x,-d.z);pitch=T.MathUtils.clamp(Math.atan2(d.y,Math.hypot(d.x,d.z)),-.75,.75);camera.rotation.set(pitch,yaw,0,'YXZ');}
function fitOverview(){camera.fov=43;camera.updateProjectionMatrix();const target=new T.Vector3(-5.8,.8,0),dir=new T.Vector3(...(camera.aspect<1?[.85,1.4,1.1]:[1.2,1.1,1.4])).normalize(),right=new T.Vector3().crossVectors(new T.Vector3(0,1,0),dir).normalize(),up=new T.Vector3().crossVectors(dir,right);const tan=Math.tan(T.MathUtils.degToRad(camera.fov/2));let distance=0;for(const x of [-24.5,12.5])for(const y of [-.3,4])for(const z of [-9.8,9.8]){const d=new T.Vector3(x,y,z).sub(target);distance=Math.max(distance,d.dot(dir)+Math.abs(d.dot(right))/(tan*camera.aspect),d.dot(dir)+Math.abs(d.dot(up))/tan);}camera.position.copy(target).addScaledVector(dir,distance*1.15);orbit.target.copy(target);orbit.update();dirty=true;}
function resetStick(){stickId=null;stick={x:0,y:0};$('#stick-knob').style.transform='translate(0px,0px)';}
function clearMovement(){keys.clear();resetStick();look=null;}
function updateChrome(){const walk=mode==='walk';$('#overview').setAttribute('aria-pressed',String(!walk));$('#walk').setAttribute('aria-pressed',String(walk));$('#joystick').hidden=!walk||!isMobile()||!!sheet;$('#walk-guide').hidden=!walk||!isMobile()||!!sheet;$('#crosshair').hidden=!walk||isMobile()||!!sheet;$('#hint').hidden=walk&&isMobile();$('#hint').textContent=walk?'WASD o flechas para caminar · Arrastra para mirar':isMobile()?'Arrastra para girar · Dos dedos para acercar':'Arrastra para girar · Rueda para acercar';$('#location').textContent=walk?places[selected].label:'Vista general';}
function setMode(next){chinches?.stop();transitionToken++;$('#fade').classList.remove('visible');closeSheets(false);clearMovement();mode=next;orbit.enabled=next==='overview';if(next==='overview')fitOverview();else{camera.fov=isMobile()?70:72;camera.updateProjectionMatrix();const d=places[selected]||places.entry;camera.position.fromArray(d.eye);updateAngles(new T.Vector3(...d.target));}updateChrome();dirty=true;if(!isMobile())mount.focus({preventScroll:true});}
async function visit(id){if(!places[id])return;chinches?.stop();closeSheets(false);clearMovement();selected=id;const token=++transitionToken;$('#fade').classList.add('visible');await new Promise(r=>setTimeout(r,matchMedia('(prefers-reduced-motion:reduce)').matches?0:130));if(token!==transitionToken)return;mode='walk';orbit.enabled=false;camera.fov=isMobile()?70:72;camera.updateProjectionMatrix();camera.position.fromArray(places[id].eye);updateAngles(new T.Vector3(...places[id].target));updateChrome();dirty=true;$('#fade').classList.remove('visible');if(!isMobile())mount.focus({preventScroll:true});}
function showSheet(id){chinches?.stop();closeSheets(false);lastFocus=document.activeElement;clearMovement();sheet=id;document.querySelector('header').inert=true;for(const e of mount.parentElement.children)if(!e.classList.contains('sheet')&&e.id!=='scrim')e.inert=true;$('#'+id).hidden=false;$('#scrim').hidden=false;$('#'+id).scrollTop=0;orbit.enabled=false;$('#nearby').hidden=true;updateChrome();$('#'+id+' .close').focus({preventScroll:true});}
function closeSheets(focus=true){document.querySelectorAll('.sheet').forEach(e=>e.hidden=true);$('#scrim').hidden=true;document.querySelector('header').inert=false;for(const e of mount.parentElement.children)e.inert=false;const restore=lastFocus;sheet=null;clearMovement();orbit.enabled=mode==='overview';updateChrome();if(focus&&restore?.isConnected)restore.focus({preventScroll:true});dirty=true;}
function openPanel(id){const d=panels[id];if(!d)return;$('#panel-tag').textContent=d.tag;$('#panel-title').innerHTML=d.title;$('#panel-body').innerHTML=d.body;showSheet('panel');chinches.bindPanel(id);if(id==='case'&&window.CubefarmYOD){const button=document.createElement('button');button.className='open-agent-panel';button.textContent='Abrir panel de agentes';button.onclick=()=>window.CubefarmYOD.open('chat');$('#panel-body').prepend(button);}}
$('#overview').onclick=()=>setMode('overview');$('#walk').onclick=()=>setMode('walk');$('#areas-open').onclick=()=>showSheet('areas');$('#help-open').onclick=()=>showSheet('help');$('#case-open').onclick=async()=>{await visit('case');openPanel('case');};document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>visit(b.dataset.place));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeSheets());$('#scrim').onclick=()=>closeSheets();$('#nearby').onclick=()=>near&&openPanel(near);
function allowed(x,z){const inside=b=>x>=b.minX&&x<=b.maxX&&z>=b.minZ&&z<=b.maxZ;if(!inside(office.bounds)&&!inside(office.annex))return false;return !office.collisions.some(c=>x>c.minX-.22&&x<c.maxX+.22&&z>c.minZ-.22&&z<c.maxZ+.22);}
function movement(dt){let forward=(keys.has('w')||keys.has('ArrowUp')?1:0)-(keys.has('s')||keys.has('ArrowDown')?1:0)-stick.y,sideways=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0)+stick.x;const length=Math.hypot(forward,sideways);if(length<.05)return false;const speed=2.1*dt/Math.max(1,length),dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*sideways)*speed,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*sideways)*speed;const steps=Math.ceil(Math.max(Math.abs(dx),Math.abs(dz))/.1)||1;for(let i=0;i<steps;i++){if(allowed(camera.position.x+dx/steps,camera.position.z))camera.position.x+=dx/steps;if(allowed(camera.position.x,camera.position.z+dz/steps))camera.position.z+=dz/steps;}return true;}
function updateNear(){near=null;let distance=2.3;for(const [id,p] of Object.entries(places)){if(id==='entry')continue;const d=camera.position.distanceTo(new T.Vector3(...p.eye));if(d<distance){distance=d;near=id;}}if(selected==='case'&&camera.position.distanceTo(new T.Vector3(...places.case.eye))<2)near='case';const show=!!near&&mode==='walk'&&!sheet;$('#nearby').hidden=!show;if(show)$('#nearby').textContent=near==='case'?'Abrir ficha del terreno':'Ver '+places[near].label;}
window.addEventListener('keydown',e=>{if(agentOverlay)return;if(e.key==='Escape'){closeSheets();return;}if(sheet){if(e.key==='Tab'){const nodes=[...$('#'+sheet).querySelectorAll('button,a[href]')],first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}return;}const k=e.key.length===1?e.key.toLowerCase():e.key;if(mode==='walk'&&['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(k)){e.preventDefault();keys.add(k);}if(k==='e'&&near)openPanel(near);});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',clearMovement);document.addEventListener('visibilitychange',()=>{clearMovement();last=performance.now();});
const base=$('#stick-base');function updateStick(e){const rect=base.getBoundingClientRect(),dx=e.clientX-(rect.x+rect.width/2),dy=e.clientY-(rect.y+rect.height/2),length=Math.hypot(dx,dy),limit=35*rect.width/112,factor=Math.min(1,limit/(length||1));const x=dx*factor,y=dy*factor;stick={x:Math.abs(x)<3?0:x/limit,y:Math.abs(y)<3?0:y/limit};$('#stick-knob').style.transform=`translate(${x*112/rect.width}px,${y*112/rect.width}px)`;}
base.addEventListener('pointerdown',e=>{if(stickId!==null)return;e.preventDefault();e.stopPropagation();stickId=e.pointerId;base.setPointerCapture(e.pointerId);updateStick(e);});base.addEventListener('pointermove',e=>{if(e.pointerId===stickId){e.preventDefault();updateStick(e);}});for(const name of ['pointerup','pointercancel','lostpointercapture'])base.addEventListener(name,e=>{if(e.pointerId===stickId)resetStick();});
const raycaster=new T.Raycaster();let press=null;const pointers=new Set();renderer.domElement.addEventListener('pointerdown',e=>{if(sheet)return;pointers.add(e.pointerId);press={x:e.clientX,y:e.clientY,id:e.pointerId,multiple:pointers.size>1};if(mode==='walk'&&look===null){look={id:e.pointerId,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId);}if(!isMobile())mount.focus({preventScroll:true});});
renderer.domElement.addEventListener('pointermove',e=>{if(mode==='walk'&&look?.id===e.pointerId&&!sheet){const dx=e.clientX-look.x,dy=e.clientY-look.y;yaw-=dx*.0036;pitch=T.MathUtils.clamp(pitch-dy*.0036,-.75,.75);camera.rotation.set(pitch,yaw,0,'YXZ');look.x=e.clientX;look.y=e.clientY;dirty=true;}});
function release(e,cancel=false){pointers.delete(e.pointerId);if(look?.id===e.pointerId)look=null;if(!cancel&&press&&press.id===e.pointerId&&!press.multiple&&pointers.size===0&&Math.hypot(e.clientX-press.x,e.clientY-press.y)<7&&!sheet){const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=[];for(const pick of office.pickBoxes){const p=raycaster.ray.intersectBox(new T.Box3(new T.Vector3(...pick.min),new T.Vector3(...pick.max)),new T.Vector3());if(p)hits.push({id:pick.id,d:p.distanceTo(camera.position)});}hits.sort((a,b)=>a.d-b.d);if(chinches.isSelecting()){const surface=raycaster.intersectObject(office.model,true).find(hit=>{const {x,y,z}=hit.point;const within=b=>x>=b.minX&&x<=b.maxX&&z>=b.minZ&&z<=b.maxZ;return y>=-.35&&y<=5&&(within(office.bounds)||within(office.annex));});if(surface)chinches.selectPoint(surface.point.toArray());}else{const selection=chooseOfficeHit({avatarHit:raycaster.intersectObjects(pilot.pickables(),true)[0],boxHits:hits,sceneHits:raycaster.intersectObject(office.model,true)});if(selection?.type==='avatar')pilot.selectIntersection(selection.hit);else if(selection?.type==='panel')openPanel(selection.id);}}press=null;}
renderer.domElement.addEventListener('pointerup',e=>release(e));renderer.domElement.addEventListener('pointercancel',e=>release(e,true));renderer.domElement.addEventListener('lostpointercapture',e=>{if(look?.id===e.pointerId)look=null;});
orbit.addEventListener('change',()=>{dirty=true;});
function resize(){const width=mount.clientWidth,height=mount.clientHeight;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();if(mode==='overview')fitOverview();else updateChrome();dirty=true;}new ResizeObserver(resize).observe(mount);resize();setMode(isMobile()?'walk':'overview');
let shadowBaked=false;function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.1);last=now;const avatarChanged=pilot.update(now,{hidden:document.hidden,overlay:agentOverlay,reducedMotion:reducedMotion.matches});if(avatarChanged){dirty=true;if(now-avatarShadowAt>=400){renderer.shadowMap.needsUpdate=true;avatarShadowAt=now;}}if(document.hidden)return;if(mode==='walk'&&!sheet&&!agentOverlay){dirty=movement(dt)||dirty;updateNear();}else if(mode==='overview'&&!sheet&&!agentOverlay)orbit.update();if(dirty){renderer.render(scene,camera);frames++;dirty=false;if(!shadowBaked){renderer.shadowMap.autoUpdate=false;shadowBaked=true;}}}
requestAnimationFrame(animate);$('#loading').hidden=true;window.officeReady=true;renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();clearMovement();$('#fallback').hidden=false;});
window.despacho={model:office.model,scene,visit,setMode,openPanel,closeSheets,getState:()=>({mode,selected,near,sheet,position:camera.position.toArray(),rotation:camera.rotation.toArray(),frames,stick:{...stick},triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls,allowed:allowed(camera.position.x,camera.position.z),mobile:isMobile(),colliders:office.collisions.length,avatar:pilot.getState()}),allowed};

chinches=createChinches3D({readView:()=>({position:camera.position.toArray(),quaternion:camera.quaternion.toArray(),fov:camera.fov,mode}),closeSheets:()=>closeSheets(),onChange:active=>{clearMovement();$('#scene').classList.toggle('pin-selecting',active);}});

// URL contains navigation only; all business state remains in Sheets.
async function routeOffice(){const place=location.hash.slice(1);if(!Object.hasOwn(places,place))return;await visit(place);if(panels[place])openPanel(place);}
window.addEventListener('hashchange',routeOffice);
await routeOffice();

function agentsVisibility(open){agentOverlay=open;chinches?.stop();closeSheets(false);clearMovement();document.querySelector('header').inert=agentOverlay;document.getElementById('workspace').inert=agentOverlay;orbit.enabled=!agentOverlay&&mode==='overview';dirty=true;}
window.addEventListener('yod-agents-visibility',e=>agentsVisibility(e.detail===true));
if(window.CubefarmYOD?.isOpen())agentsVisibility(true);
