// Fichas locales compartidas por el recorrido y el plano.
import {panels} from './panels.js?v=7';
panels.reception={tag:'Recepción · YoDesarrollo',title:'Un Despacho que puede crecer.',body:'<p>Una recepción de madera y piedra, la marca YoDesarrollo y una circulación clara hacia los estudios de trabajo.</p><p>El diseño amplía el espacio aprobado e incorpora las referencias de Aurum en las curvas, los materiales y la relación con el patio.</p><p class="note">Versión 02. Por ahora sólo se muestra la ficha de Caso; las tareas de MOAC aún no están conectadas.</p><a href="diseno.html">Ver las referencias de Aurum</a>'};
panels.patio={tag:'Patio central',title:'El punto de encuentro.',body:'<p>Un olivo, piedra natural y vegetación baja organizan el centro del Despacho. Los pasillos a ambos lados permiten recorrer las áreas sin pasar entre los puestos de trabajo.</p><p>El patio sirve como referencia para orientarte en todo momento.</p>'};
panels.potential={tag:'Estudio 01 · Potenciales',title:'Aquí comienza cada terreno.',body:'<p>Un área para entender el predio, verificar sus posibilidades y preparar el Plan de Potencial.</p><p>Toca al autón de tu proyecto o elige Abrir puesto. Su plan de potencial y la conversación se abren juntos.</p>'};
panels.projects={tag:'Estudio 02',title:'Proyectos y permisos.',body:'<p>Espacio previsto para los casos que avanzan en diseño, normativa, trámites y permisos.</p><p>Los puestos se agrupan alrededor de un área propia, con separación visual respecto al estudio de Potenciales.</p><p class="note">Área preparada para la futura conexión de MOAC. No contiene tareas activas en esta versión.</p>'};
panels.delivery={tag:'Estudio 03',title:'Obra y ventas.',body:'<p>Espacio previsto para dar seguimiento a ejecución y comercialización, conservando el vínculo con el mismo terreno y su historia.</p><p class="note">La asignación de tareas a esta área se conectará con MOAC; los puestos actuales no representan tareas cargadas.</p>'};
panels.lounge={tag:'Sala de encuentro',title:'Revisar con otra perspectiva.',body:'<p>Una sala para conversaciones y revisión conjunta, con mobiliario tapizado, madera, piedra y una biblioteca de proyectos.</p><p>Permite reunir a quienes participan en un caso sin ocupar su área de trabajo.</p>'};

panels.editing={tag:'Sala de edición · Embudo comercial',title:'Producir, revisar y aprender.',body:'<p>Un ala propia para reunir la producción de contenido y la visión comercial de YoDesarrollo y Aurum.</p><h3>La mesa de Alejandro y Sayri</h3><p>Dos lugares para revisar propuestas, pedir cambios y tomar decisiones editoriales. Los clientes y socios pueden participar como lectores; la producción propone y reporta.</p><h3>Los puestos de trabajo</h3><ul><li><b>Guion y propuesta:</b> ideas, mensaje, audiencia y objetivo.</li><li><b>Producción:</b> guion, láminas, voz y video, con sus versiones.</li><li><b>Comercial y medición:</b> campañas, publicaciones, pauta, leads, citas y seguimiento.</li></ul><h3>Dos pantallas, una visión común</h3><p>La mesa editorial muestra qué falta revisar. El embudo muestra el recorrido desde el inicio, incluyendo las caídas entre etapas, y los dos imanes: Arquitectura de Autor y Plan de Potencial.</p><p class="note">Distribución basada en los procesos documentados de Sala de Edición y Embudo comercial. Las pantallas son un esquema; no muestran cifras ni ejecutan decisiones.</p><p><a href="https://yodesarrollomx.github.io/sala-edicion/" target="_blank" rel="noopener">Abrir la Sala de Edición actual</a></p><p><a href="https://yodesarrollomx.github.io/aurum-board/" target="_blank" rel="noopener">Abrir el Embudo comercial actual</a></p>'};
panels.editorial={tag:'Pantalla de revisión editorial',title:'Lo que necesita una decisión.',body:'<p>Propuestas → decisión editorial → producción por etapas → correcciones → aprobación final.</p><p>Los guiones se leen, las láminas se ven, las voces se escuchan y el video se revisa en movimiento. La sala reserva una pantalla amplia y la mesa de los dos editores para respetar cada formato.</p><p>Una pieza con una petición abierta necesita resolverla antes de avanzar.</p><p class="note">Esquema del proceso documentado. La conexión con las propuestas y decisiones reales será otro bloque.</p>'};
panels.funnel={tag:'Pantalla del embudo comercial',title:'Del primer contacto al siguiente paso.',body:'<p>Aquí se reunirán las publicaciones de Facebook e Instagram, el gasto de pauta, los leads y las citas, y los recorridos de Arquitectura de Autor y Plan de Potencial.</p><p>La vista debe comenzar en Inicio y mostrar también los abandonos. No confundiremos una cita con una venta ni atribuiremos un cierre a una campaña sin evidencia.</p><p class="note">La documentación acredita esos módulos; en este bloque no se comprobó su ejecución en vivo ni se cargaron métricas.</p>'};

panels.editing={tag:'Sala de edición · Embudo comercial',title:'Tu mesa de trabajo.',body:'<p>Revisión editorial, producción y seguimiento comercial con acceso a los tableros actuales.</p><p><a href="sala.html">Entrar a la mesa de trabajo</a></p><p class="note">Los datos y las decisiones permanecen en sus sistemas de origen. La oficina todavía no los carga en vivo.</p>'};
panels.editorial={tag:'Mesa de Alejandro y Sayri',title:'Revisión editorial.',body:'<p>Propuestas, correcciones y aprobación de las etapas de producción.</p><p><a href="sala.html#editorial">Abrir revisión editorial</a></p>'};
panels.funnel={tag:'Comercial y medición',title:'El embudo completo.',body:'<p>Consulta publicaciones, pauta, leads, citas y seguimiento en el tablero comercial.</p><p><a href="sala.html#comercial">Abrir estación comercial</a></p>'};

export {panels};
