'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const load=()=>import('../despacho3d/goals.mjs');
const caseId='case-synthetic';
const draft={title:'Diagnóstico sintético',instruction:'Leer la información sintética y preparar tareas.',criterion:'Evidencia revisable.'};
const selection={case_id:caseId,goals:{schema:1,ready:true,worker_ready:false}};
function goal(overrides={}){return {goal_id:'goal-synthetic',case_id:caseId,...draft,scope:'local_analysis_v1',status:'queued',source_revision:'source-1',revision:'goal-1',sequence:0,created_at:'2026-10-03T00:00:00Z',updated_at:'2026-10-03T00:00:00Z',tasks:[],evidence:[],summary:'',...overrides};}
function backend(){
 const state={source_revision:'source-1',goals:[]},calls=[],receipts=new Map();
 return {state,calls,receipts,readGoals:async payload=>{calls.push({op:'readGoals',payload});return {ok:true,schema:1,...structuredClone(state)};},createGoal:async payload=>{calls.push({op:'createGoal',payload});if(receipts.has(payload.request_id))return structuredClone(receipts.get(payload.request_id));if(payload.expected_revision!==state.source_revision)return {ok:false,error:'stale_revision'};const created=goal({...payload,goal_id:'goal-'+receipts.size,source_revision:payload.expected_revision});delete created.request_id;delete created.expected_revision;state.goals.push(created);const ack={ok:true,request_id:payload.request_id,goal:structuredClone(created)};receipts.set(payload.request_id,ack);return ack;},reviewGoal:async payload=>{calls.push({op:'reviewGoal',payload});if(receipts.has(payload.request_id))return structuredClone(receipts.get(payload.request_id));const item=state.goals.find(row=>row.goal_id===payload.goal_id);if(!item||item.revision!==payload.expected_revision)return {ok:false,error:'stale_revision'};Object.assign(item,{status:{approve:'completed',resume:'queued',stop:'stopped'}[payload.action],revision:'goal-'+(receipts.size+2),updated_at:new Date(Date.parse(item.updated_at)+1000).toISOString()});const ack={ok:true,request_id:payload.request_id,goal:structuredClone(item)};receipts.set(payload.request_id,ack);return ack;}};
}
async function harness(){const {DurableGoals}=await load(),server=backend();let context={selection:structuredClone(selection),busy:false},counter=0,denied=0;const controller=new DurableGoals({transport:server,getContext:()=>context,uuid:()=>`request-${++counter}`,onUnauthorized:()=>{denied++;context=null;}});return {server,controller,context:value=>context=value,denied:()=>denied};}
test('read-only goal dashboard never executes; offline motor still permits an explicit queued goal',async()=>{
 const h=await harness();await h.controller.read();assert.deepEqual(h.server.calls.map(c=>c.op),['readGoals']);assert.equal(await h.controller.create(draft),true);assert.equal(h.controller.model.goals[0].status,'queued');assert.equal(h.server.calls[1].payload.scope,'local_analysis_v1');assert.equal(h.server.calls[1].payload.expected_revision,'source-1');assert.equal(await h.controller.create(draft),false);assert.equal(h.server.state.goals.length,1);
});
test('lost creation acknowledgement survives readback and retries its exact original request, without duplicating the goal',async()=>{
 const h=await harness(),create=h.server.createGoal;let lose=true;h.server.createGoal=async p=>{const ack=await create(p);if(lose){lose=false;throw Error('lost');}return ack;};await h.controller.read();assert.equal(await h.controller.create(draft),false);const pending=structuredClone(h.controller.pending);assert.equal(h.controller.status,'unconfirmed');await h.controller.read();assert.equal(h.controller.model.goals.length,1);assert.deepEqual(h.controller.pending,pending);assert.equal(await h.controller.create({...draft,title:'Different'}),false);assert.equal(await h.controller.retry(),true);const writes=h.server.calls.filter(c=>c.op==='createGoal');assert.deepEqual(writes[0],writes[1]);assert.equal(h.server.state.goals.length,1);assert.equal(h.controller.pending,null);
});
test('replaying a receipt cannot overwrite newer progress observed in Sheets',async()=>{
 const h=await harness(),create=h.server.createGoal;let fail=true;h.server.createGoal=async p=>{const ack=await create(p);if(fail){fail=false;throw Error('lost');}return ack;};await h.controller.read();await h.controller.create(draft);Object.assign(h.server.state.goals[0],{status:'running',sequence:1,summary:'Avance ya guardado',updated_at:'2026-10-03T00:02:00Z'});await h.controller.read();assert.equal(await h.controller.retry(),true);assert.equal(h.controller.model.goals[0].summary,'Avance ya guardado');assert.equal(h.controller.model.goals[0].status,'running');
});
test('reviews use goal revision and gate completion, resume and cancellation by canonical state',async()=>{
 const h=await harness();h.server.state.goals=[goal()];await h.controller.read();assert.equal(await h.controller.review('goal-synthetic','approve'),false);assert.equal(await h.controller.review('goal-synthetic','resume'),false);assert.equal(await h.controller.review('goal-synthetic','stop'),true);assert.equal(h.server.calls.at(-1).payload.expected_revision,'goal-1');assert.equal(await h.controller.review('goal-synthetic','resume'),true);assert.equal(h.controller.model.goals[0].status,'queued');Object.assign(h.server.state.goals[0],{status:'ready_for_review',revision:'review-1',updated_at:'2026-10-03T00:03:00Z'});await h.controller.read();assert.equal(await h.controller.review('goal-synthetic','approve'),true);assert.equal(h.controller.model.goals[0].status,'completed');
});
test('late reads and writes cannot restore goal data after hiding or revoking a case',async()=>{
 const h=await harness();let release;h.server.readGoals=()=>new Promise(resolve=>release=resolve);const reading=h.controller.read();h.controller.hide();release({ok:true,schema:1,source_revision:'source-1',goals:[goal()]});assert.equal(await reading,false);assert.equal(h.controller.model,null);const h2=await harness();await h2.controller.read();h2.server.createGoal=()=>new Promise(resolve=>release=resolve);const writing=h2.controller.create(draft);h2.controller.reset();release({ok:true,request_id:'request-1',goal:goal()});assert.equal(await writing,false);assert.equal(h2.controller.model,null);assert.equal(h2.controller.pending,null);
});
test('stale revision requires refreshed evidence; permission denial clears all private goal state',async()=>{
 const h=await harness();await h.controller.read();h.server.state.source_revision='source-2';assert.equal(await h.controller.create(draft),false);assert.equal(h.controller.pending,null);assert.equal(h.controller.status,'conflict');await h.controller.read();assert.equal(await h.controller.create(draft),true);h.server.readGoals=async()=>({ok:false,error:'unauthorized',detail:'private server detail'});assert.equal(await h.controller.read(),false);assert.equal(h.controller.model,null);assert.equal(h.controller.pending,null);assert.equal(h.denied(),1);assert.ok(!h.controller.notice.includes('private'));
});
test('unknown provider errors stay private and keep mutation IDs until confirmed',async()=>{
 const h=await harness();await h.controller.read();h.server.createGoal=async()=>{throw Error('private token from provider');};await h.controller.create(draft);assert.equal(h.controller.status,'unconfirmed');assert.ok(h.controller.pending);assert.ok(!h.controller.notice.includes('private token'));h.server.createGoal=async p=>({ok:true,request_id:'different-id',goal:goal()});assert.equal(await h.controller.retry(),false);assert.ok(h.controller.pending);
});
test('bounded goal schema rejects cross-case records, lease secrets and invalid task evidence',async()=>{
 const {validateGoals,validateGoal}=await load();const base=goal();assert.equal(validateGoal(base,caseId).goal_id,base.goal_id);for(const change of [{case_id:'other'},{lease_token:'secret'},{sequence:-1},{sequence:0.1},{status:'made-up'},{tasks:Array(9).fill({})}])assert.throws(()=>validateGoal({...base,...change},caseId),/invalid_goals/);const evidenced=goal({tasks:[{id:'task-1',title:'Comprobar',criterion:'Dato concreto',status:'ready_for_review',summary:'Preparado',evidence_ids:['ev-1']}],evidence:[{id:'ev-1',task_id:'task-1',title:'Fuente',text:'Dato sintético',sha256:'a'.repeat(64),bytes:15}]});assert.equal(validateGoal(evidenced,caseId).evidence.length,1);assert.throws(()=>validateGoal({...evidenced,evidence:[{...evidenced.evidence[0],bytes:14}]},caseId),/invalid_goals/);assert.throws(()=>validateGoal({...evidenced,evidence:[]},caseId),/invalid_goals/);assert.throws(()=>validateGoals({ok:true,schema:1,source_revision:'s',goals:[base,base]},caseId),/invalid_goals/);
});
test('visible polling is read-only, waits for each read, and cancels while hidden or disposed',async()=>{
 const {watchGoals}=await load(),timers=[];let visible=false,reads=0,release,cleared;const controller={busy:false,read:async()=>{reads++;await new Promise(resolve=>release=resolve);}};const stop=watchGoals(controller,{visible:()=>visible,setTimer:(fn,ms)=>{assert.equal(ms,8000);timers.push(fn);return timers.length;},clearTimer:value=>cleared=value});assert.equal(reads,0);visible=true;const tick=timers.shift()();assert.equal(reads,1);assert.equal(timers.length,0);stop();release();await tick;assert.equal(timers.length,0);assert.equal(cleared,1);
});
function bridgeHarness(){const listeners={},posts=[],source={postMessage:value=>posts.push(value)},calls=[];let epoch=1;const root={globalThis:null,location:{origin:'https://portal.invalid'},setTimeout,clearTimeout,addEventListener:(event,fn)=>listeners[event]=fn,removeEventListener:event=>delete listeners[event]};root.globalThis=root;vm.runInNewContext(fs.readFileSync(require.resolve('../os/despacho-conversation.js'),'utf8'),root);root.YodDespachoConversation.bind({isAuthorized:()=>true,getIframeWindow:()=>source,getEpoch:()=>epoch,getTransport:()=>Object.fromEntries(['readGoals','createGoal','reviewGoal'].map(op=>[op,async payload=>{calls.push({op,payload});return {ok:true};}]))});return {calls,posts,source,epoch:value=>epoch=value,send:(method,payload,extra={})=>listeners.message({origin:root.location.origin,source,data:{type:'yod:case:request',version:1,id:'bridge-request',method,payload},...extra})};}
test('OS goal bridge accepts only exact bounded actor payloads from the authorized frame',async()=>{
 const h=bridgeHarness(),payload={case_id:caseId,request_id:'request-synthetic',expected_revision:'source-1',...draft,scope:'local_analysis_v1'};await h.send('createGoal',payload);assert.equal(h.calls.length,1);await h.send('createGoal',{...payload,target:'attacker-sheet'});await h.send('createGoal',{...payload,scope:'unrestricted'});await h.send('createGoal',{...payload,instruction:'x'.repeat(4001)});await h.send('createGoal',payload,{origin:'https://evil.invalid'});await h.send('createGoal',payload,{source:{}});assert.equal(h.calls.length,1);await h.send('readGoals',{case_id:caseId});await h.send('reviewGoal',{case_id:caseId,goal_id:'goal-synthetic',request_id:'request-review',expected_revision:'goal-1',action:'approve'});await h.send('reviewGoal',{case_id:caseId,goal_id:'goal-synthetic',request_id:'request-review',expected_revision:'goal-1',action:'complete_business'});assert.equal(h.calls.length,3);
});
test('authenticated transport signs actor operations only with current session and rejects extra authority',async()=>{
 const calls=[];let session={ready:true,allowed:true,token:'synthetic-private-session',epoch:1},release;const root={globalThis:null,AbortController,setTimeout,clearTimeout,fetch:async(url,request)=>{calls.push({url,request});if(release===null)await new Promise(resolve=>release=resolve);return {ok:true,text:async()=>'{"ok":true}'};}};root.globalThis=root;vm.runInNewContext(fs.readFileSync(require.resolve('../os/despacho-transport.js'),'utf8'),root);const transport=root.YodDespachoTransport.create({endpoint:'https://script.google.com/macros/s/SYNTHETIC/exec',getSession:()=>session});await transport.readGoals({case_id:caseId});const body=JSON.parse(calls[0].request.body);assert.equal(body.operation,'readGoals');assert.equal(body.k,session.token);assert.ok(!calls[0].url.includes(session.token));await assert.rejects(transport.readGoals({case_id:caseId,actor:'different'}),/invalid_payload/);release=null;const pending=transport.readGoals({case_id:caseId});session={...session,epoch:2,token:'changed'};release();await assert.rejects(pending,/session_changed/);assert.equal(calls.length,2);
});
test('background goal polling never blocks conversation reads or message delivery as a lost connection',async()=>{
 const listeners={},posts=[],calls=[],source={postMessage:value=>posts.push(value)};let release;
 const root={globalThis:null,location:{origin:'https://portal.invalid'},setTimeout,clearTimeout,addEventListener:(event,fn)=>listeners[event]=fn,removeEventListener:()=>{}};root.globalThis=root;vm.runInNewContext(fs.readFileSync(require.resolve('../os/despacho-conversation.js'),'utf8'),root);
 const transport={readGoals:payload=>{calls.push({op:'readGoals',payload});return new Promise(resolve=>release=resolve);},resolveCurrent:async()=>({ok:true,case_id:caseId}),enqueue:async payload=>{calls.push({op:'enqueue',payload});return {ok:true,request_id:payload.request_id};}};
 root.YodDespachoConversation.bind({isAuthorized:()=>true,getIframeWindow:()=>source,getEpoch:()=>1,getTransport:()=>transport});
 const send=(method,payload,id)=>listeners.message({origin:root.location.origin,source,data:{type:'yod:case:request',version:1,id,method,payload}});
 const polling=send('readGoals',{case_id:caseId},'background');await send('resolveCurrent',{},'conversation-read');await send('enqueue',{case_id:caseId,request_id:'original-write',expected_revision:'source-1',message:'Texto sintético'},'conversation-write');await send('readGoals',{case_id:caseId},'redundant-poll');
 assert.equal(posts.find(item=>item.id==='conversation-read').result.case_id,caseId);assert.equal(posts.find(item=>item.id==='conversation-write').result.request_id,'original-write');assert.equal(posts.find(item=>item.id==='redundant-poll').error,'transport_busy');assert.equal(calls.filter(item=>item.op==='readGoals').length,1);assert.equal(calls.filter(item=>item.op==='enqueue').length,1);release({ok:true});await polling;assert.equal(posts.find(item=>item.id==='background').error,null);
});
test('OS preserves safe transient diagnostics and does not forward provider details',async()=>{
 const listeners={},posts=[],source={postMessage:value=>posts.push(value)};let failure=Error('timeout');
 const root={globalThis:null,location:{origin:'https://portal.invalid'},setTimeout,clearTimeout,addEventListener:(event,fn)=>listeners[event]=fn,removeEventListener:()=>{}};root.globalThis=root;vm.runInNewContext(fs.readFileSync(require.resolve('../os/despacho-conversation.js'),'utf8'),root);root.YodDespachoConversation.bind({isAuthorized:()=>true,getIframeWindow:()=>source,getEpoch:()=>1,getTransport:()=>({resolveCurrent:async()=>{throw failure;}})});
 const request=()=>listeners.message({origin:root.location.origin,source,data:{type:'yod:case:request',version:1,id:'request-synthetic',method:'resolveCurrent',payload:{}}});
 await request();assert.equal(posts.at(-1).error,'timeout');failure=Error('session_pending');await request();assert.equal(posts.at(-1).error,'session_pending');failure=Error('provider detail private');await request();assert.equal(posts.at(-1).error,'unavailable');
});
