const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const base=path.resolve(__dirname,'../despacho3d/avatars'),vendor=pathToFileURL(path.resolve(base,'../vendor/three.module.js')).href;
const cache=new Map();function url(file){if(cache.has(file))return cache.get(file);const source=fs.readFileSync(file,'utf8').replace(/from 'three'/g,`from '${vendor}'`).replace(/from '(\.\/[^']+)'/g,(_,r)=>`from '${url(path.resolve(path.dirname(file),r.split('?')[0]))}'`);const value='data:text/javascript;base64,'+Buffer.from(source).toString('base64');cache.set(file,value);return value;}
const modules=Promise.all([import(vendor),import(url(path.join(base,'avatar.mjs'))),import(url(path.join(base,'office-human.mjs')))]);
test('office humanoids keep geometry within the published no-texture budget',async()=>{const [T,{createAvatar,disposeAvatar},{OFFICE_HUMAN_FORMS,OFFICE_AVATAR_BUDGET}]=await modules;for(const form of OFFICE_HUMAN_FORMS)for(const hairStyle of ['swept','curly','bob','bun','waves','crop']){const a=createAvatar(form,'#669d79','Synthetic',{quality:'office',hairStyle,seed:'synthetic'});let meshes=0,triangles=0,textures=0;a.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;assert.ok([...o.geometry.attributes.position.array].every(Number.isFinite));textures+=Number(!!o.material.map);}});assert.ok(meshes<=OFFICE_AVATAR_BUDGET.maxMeshes,form+' meshes '+meshes);assert.ok(triangles<=OFFICE_AVATAR_BUDGET.maxTriangles,form+' triangles '+triangles);assert.equal(textures,0);const bounds=new T.Box3().setFromObject(a);assert.ok(bounds.max.y<1.90&&bounds.max.y>1.3);assert.equal(a.userData.officeHuman,true);disposeAvatar(a);}});
test('sitting solves chair contact after profile scale and all motions restore finite poses',async()=>{const [T,{createAvatar,animateAvatar,disposeAvatar}]=await modules;for(const form of ['child','young_male','woman','man']){const a=createAvatar(form,'#547f71','Synthetic',{quality:'office'}),u=a.userData;animateAvatar(a,1,false,true);assert.ok(Math.abs(u.body.position.y+u.seatContact*u.body.scale.y-.62)<1e-9);assert.equal(u.legs[0].rotation.x,-Math.PI/2);assert.equal(u.joints.knee_1.rotation.x,Math.PI/2);for(const pose of ['walk','talk','wave','deliver','idle']){animateAvatar(a,2,pose==='walk',false,pose);a.traverse(o=>assert.ok(o.matrixWorld.elements.every(Number.isFinite)));}assert.equal(u.joints.mouth.scale.y,1);const head=new T.Vector3();u.joints.head.getWorldPosition(head);assert.ok(head.y>1&&head.z===0);disposeAvatar(a);}});
test('office representation retains authorized color and independent model resources',async()=>{const [,{createAvatar,disposeAvatar}]=await modules;const a=createAvatar('man','#669d79','First',{quality:'office',seed:'ONE'}),b=createAvatar('man','#a57eae','Second',{quality:'office',seed:'TWO'});assert.notEqual(a.userData.seed,b.userData.seed);let aColor=false,bColor=false;a.traverse(o=>{if(o.material?.color?.getHexString()==='669d79')aColor=true;});b.traverse(o=>{if(o.material?.color?.getHexString()==='a57eae')bColor=true;});assert.equal(aColor,true);assert.equal(bColor,true);let bDisposed=false;b.traverse(o=>o.geometry?.addEventListener('dispose',()=>bDisposed=true));disposeAvatar(a);assert.equal(bDisposed,false);disposeAvatar(b);});

test('mouth remains a small facial feature at rest and while talking',async()=>{const [T,{createAvatar,animateAvatar,disposeAvatar}]=await modules;const avatar=createAvatar('man','#669d79','Synthetic',{quality:'office'});try{for(const action of ['idle','talk'])for(const seconds of [0,.065,.2,1.2,4.6]){animateAvatar(avatar,seconds,false,false,action);const mouth=new T.Box3().setFromObject(avatar.userData.joints.mouth).getSize(new T.Vector3());assert.ok(mouth.y>=.004&&mouth.y<.020,action+' mouth height '+mouth.y);assert.ok(mouth.x<.06&&mouth.z<.02,'mouth remains within facial proportions');}animateAvatar(avatar,1,false,false,'idle');assert.equal(avatar.userData.joints.mouth.scale.y,1);}finally{disposeAvatar(avatar);}});
