const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../os/despacho-transport.js'),'utf8');
function harness(fetch){const c=vm.createContext({AbortController,setTimeout,clearTimeout});vm.runInContext(source,c);let session={ready:true,allowed:true,token:'synthetic-session',epoch:1};return {create:(extra={})=>c.YodDespachoTransport.create({endpoint:'https://script.google.com/macros/s/synthetic/exec',getSession:()=>session,fetch,...extra}),session:s=>{session=s;}};}
test('POST retains credentials in body, uses one server and preserves the receipt',async()=>{let calls=[];const h=harness(async(url,request)=>{calls.push({url,request});return {ok:true,text:async()=>'{"ok":true,"job_id":"job-synthetic"}'};});let t=h.create();const r=await t.enqueue({request_id:'req-synthetic',message:'Texto'});assert.equal(r.job_id,'job-synthetic');assert.equal(calls.length,1);assert.ok(!calls[0].url.includes('session'));const b=JSON.parse(calls[0].request.body);assert.equal(b.k,'synthetic-session');assert.equal(b.operation,'enqueue');assert.equal(calls[0].request.credentials,'omit');assert.equal(calls[0].request.headers['Content-Type'],'text/plain;charset=UTF-8');});
test('no request without confirmed permission; session changes discard late private result',async()=>{let release,count=0;const h=harness(async()=>{count++;await new Promise(r=>release=r);return {ok:true,text:async()=>'{"ok":true}'};});h.session({ready:false});await assert.rejects(h.create().read({}),/unauthorized/);assert.equal(count,0);h.session({ready:true,allowed:true,token:'a',epoch:1});const pending=h.create().read({});h.session({ready:true,allowed:true,token:'b',epoch:2});release();await assert.rejects(pending,/session_changed/);});
test('invalid endpoints and oversized responses fail closed without fallback',async()=>{let count=0;const h=harness(async()=>{count++;return {ok:true,text:async()=>'x'.repeat(524289)};});assert.throws(()=>h.create({endpoint:'https://example.test/exec'}),/invalid_endpoint/);assert.throws(()=>h.create({endpoint:'https://script.google.com/macros/s/x/exec?k=secret'}),/invalid_endpoint/);await assert.rejects(h.create().resolveCurrent({}),/response_limit/);assert.equal(count,1);});
test('temporary validation pending does not send a write or impersonate a revoked session',async()=>{let calls=0;const h=harness(async()=>{calls++;return {ok:true,text:async()=>'{"ok":true}'};});h.session({ready:false,allowed:true,token:'same-session',epoch:1});await assert.rejects(h.create().enqueue({request_id:'request-original',message:'Texto'}),/session_pending/);assert.equal(calls,0);h.session({ready:true,allowed:true,token:'same-session',epoch:1});await h.create().read({});assert.equal(calls,1);});
test('same-session readiness loss suppresses private response without claiming an identity change',async()=>{let release;const h=harness(async()=>{await new Promise(resolve=>release=resolve);return {ok:true,text:async()=>'{"ok":true,"private":"synthetic"}'};});const session={ready:true,allowed:true,token:'same-session',epoch:1};h.session(session);const request=h.create().read({});session.ready=false;release();await assert.rejects(request,/session_pending/);});
test('actual permission revocation and in-place epoch changes fence late responses',async()=>{let release;const h=harness(async()=>{await new Promise(resolve=>release=resolve);return {ok:true,text:async()=>'{"ok":true}'};});const session={ready:true,allowed:true,token:'same-session',epoch:1};h.session(session);let request=h.create().read({});session.allowed=false;release();await assert.rejects(request,/unauthorized/);session.allowed=true;request=h.create().read({});session.epoch=2;release();await assert.rejects(request,/session_changed/);});
test('fetch timeout stays transient and never retries a mutation behind the caller',async()=>{const calls=[];const h=harness(async(url,request)=>{calls.push(JSON.parse(request.body));await new Promise((resolve,reject)=>request.signal.addEventListener('abort',()=>{const error=Error('aborted');error.name='AbortError';reject(error);},{once:true}));});await assert.rejects(h.create({timeout:5}).enqueue({request_id:'original-mutation',message:'Texto sintético'}),/timeout/);assert.equal(calls.length,1);assert.equal(calls[0].payload.request_id,'original-mutation');});
